services:
  kafka:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      
      KAFKA_LISTENERS: "CONTROLLER://:29093,INTERNAL://:19092,EXTERNAL://:9092"

      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker:19092,EXTERNAL://localhost:9092"

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s


  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bike-fleet
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -psecret"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s


  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test:
        ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

    
  producer:
    build:
      context: ./Producer
      dockerfile: Dockerfile
    container_name: bike.producer
    environment:
      Kafka__BootstrapServers: broker:19092
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure


  processor:
    build:
      context: ./Processor
      dockerfile: Dockerfile
    container_name: bike.processor
    environment:
      Kafka__BootstrapServers: broker:19092
      Mongo__ConnectionString: mongodb://mongo:27017
      MySql__ConnectionString: Server=mysql;Port=3306;Database=bike-fleet;User=root;Password=secret;
      Redis__ConnectionString: redis:6379
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

    restart: on-failure



volumes:
  mongo-data:
  mysql-data:
  redis-data:
      
    